execute_process(
    COMMAND luarocks.bat config sysconfdir
    OUTPUT_VARIABLE LUAROCKS_SYSCONFDIR
    OUTPUT_STRIP_TRAILING_WHITESPACE
    COMMAND_ERROR_IS_FATAL ANY
)

file(TO_NATIVE_PATH "${LUAROCKS_SYSCONFDIR}" LUAROCKS_SYSCONFDIR)
file(TO_NATIVE_PATH "${LUAROCKS_EXE}" LUAROCKS_EXE)

configure_file(luarocks${EXTNAME}.in luarocks${EXTNAME} @ONLY)
configure_file(lua${EXTNAME}.in lua${EXTNAME} @ONLY)
